### ISSUE TITLE
Refused to execute script from 'https://apis.google.com/js/api.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by eromoe** [jiacai2050/gooreplacer4chrome#14]
It happens on stackoverflow `Human Verification`,
google reCaptcha lost confirm button, that 's very painful...

some solution :
http://webmasters.stackexchange.com/questions/50006/chrome-refused-to-execute-this-javascript-file
http://blog.sina.com.cn/s/blog_666d6ee10101eyh0.html

**Comment by 1354092549** [comment]
#17
