### ISSUE TITLE
why still cant i sign up in stackoverflow?

### ISSUE THREAD

**Issue by lunabird** [jiacai2050/gooreplacer4chrome#15]
I've applied gooreplacer4chrome to my chrome. When I open stackoverflow to sign up, the page still cant show any css styles.

**Comment by jiacai2050** [comment]
You can check what are missing using DevTools (Press Ctrl + Shift + C or Cmd + Shift + C on mac)

**Comment by lunabird** [comment]
I found this errors. 

GET https://cdn.sstatic.net/stackoverflow/all.css?v=f29b1dcb2836 net::ERR_CONNECTION_TIMED_OUT
GET https://cdn.sstatic.net/Js/stub.en.js?v=dee868fd2500 net::ERR_CONNECTION_TIMED_OUT
GET https://cdn.sstatic.net/Js/auth.en.js?v=de0917acada9 net::ERR_CONNECTION_TIMED_OUT

**Comment by jiacai2050** [comment]
Now I think  you understand why sign up page is still losing css.
You can host these css and js files by your own, then customize rules for redirecting
