### ISSUE TITLE
force_install_for_windows.reg

### ISSUE THREAD

**Issue by klxy1990** [jiacai2050/gooreplacer4chrome#22]
这个对应的超链接 点开并没有下载···force_install_for_windows.reg这个注册表啊。
页面内容是这个
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist]
"1"="paopmncpffekhhffcndhnmjincfplbma;https://github.com/jiacai2050/gooreplacer4chrome/raw/master/updates.xml"

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Chromium\ExtensionInstallForcelist]
"1"="paopmncpffekhhffcndhnmjincfplbma;https://github.com/jiacai2050/gooreplacer4chrome/raw/master/updates.xml"

**Comment by Mrrjez** [comment]
你在最上面（clone or download），不是点下面的超链接。
下下来zip里面有force_install_for_windows.reg

**Comment by bpplpp** [comment]
强制注册表以后，重启浏览器再次安装也没有用啊。

**Comment by jiacai2050** [comment]
这是因为 gooreplacer 更换过了一次地址。
此外，Chrome 自 44 版本以后也禁止从本地安装插件了，建议你们找个能翻墙的环境，把这个插件下下来，以后就能用了。
