### ISSUE TITLE
chrome安装扩展之后无法启用

### ISSUE THREAD

**Issue by chongyuan** [jiacai2050/gooreplacer4chrome#25]
chrome安装扩展之后，“启用”的地方是灰色的无法点击；

**Comment by chongyuan** [comment]
![b4561615-4089-487f-8596-976ceb9342f9](https://cloud.githubusercontent.com/assets/8692564/19486071/b8416d40-958f-11e6-89f2-470f649dfc34.png)

**Comment by jiacai2050** [comment]
你说的这个地方不能启用呀，这是新版Chrome 的限制，[只能安装](https://support.google.com/chrome/answer/2811969?visit_id=1-636124452553472962-2733404062&p=ui_remove_non_cws_extensions&hl=en&rd=1)来自应用商店的扩展。
