### ISSUE TITLE
与HTTPS Everywhere冲突

### ISSUE THREAD

**Issue by ivysrono** [jiacai2050/gooreplacer4chrome#5]
http开头者会被优先重定向到google的https地址。
虽然我这还是穿越了能访问的，但能否做到二次重定向？

**Comment by jiacai2050** [comment]
Google 开发指南有说明，如果有多个扩展都去修改 请求，那么最新安装的扩展 拥有修改权。
- https://developer.chrome.com/extensions/webRequest
